# ----------------------------------------------------------------------------
# Editor Configurations
# ----------------------------------------------------------------------------


# theme ----------------------------------------------------------------------
theme = "gruvbox_dark_hard_transparent"
# ----------------------------------------------------------------------------


# Editor ---------------------------------------------------------------------
[editor]
scrolloff                   = 10
scroll-lines                = 5
shell                       = ["fish", "-c"]
line-number                 = "relative"
cursorline                  = true
cursorcolumn                = true
gutters                     = ["diagnostics", "line-numbers", "spacer", "diff"]
idle-timeout                = 0
rulers                      = [80,]
bufferline                  = "always"
color-modes                 = true
# ----------------------------------------------------------------------------


# Statusline -----------------------------------------------------------------
[editor.statusline]
left                        = [
  "mode",
  "file-name",
  "file-modification-indicator",
  "selections"
]
center                      = [
  "spinner",
  "file-type",
  "diagnostics",
  "spacer",
  "workspace-diagnostics",
]
right                       = [
  "position",
  "position-percentage",
  "total-line-numbers",
  "file-encoding",
  "file-line-ending"
]
separator                   = " "
mode.normal                 = " Normal"
mode.insert                 = "󰛓 Insert"
mode.select                 = "󱖲 Select"
# ----------------------------------------------------------------------------


# LSP -------------------------------------------------------------------------
[editor.lsp]
display-messages            = true
display-inlay-hints         = true
# ----------------------------------------------------------------------------


# Cursor Shape ----------------------------------------------------------------
# [editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"
# -----------------------------------------------------------------------------

# Whitespace Render -----------------------------------------------------------
# [editor.whitespace]
# render                      = "all"

[editor.whitespace.characters]
# space                       = "·"
nbsp                        = "⍽"
tab                         = "→"
newline                     = "⏎"
tabpad                      = "·"
# ----------------------------------------------------------------------------

# Indent guides --------------------------------------------------------------
[editor.indent-guides]
render                      = true
character                   = "│"
skip-levels                 = 0
# ----------------------------------------------------------------------------

# Keymaps --------------------------------------------------------------

[keys.normal.space]
"." = "file_picker_in_current_directory" 
F = "no_op"





[keys.normal.space.t]
r = ":config-reload"


# ----------------------------------------------------------------------------

