use-grammars = { only = [
  "rust",
  "javascript",
  "typescript",
  "rescript",
  "json",
  "toml",
  "just",
  "odin",
  "scheme",
] }

[[language]]
name = "odin"
auto-format = false
scope = "source.odin"
file-types = ["odin", "tea"]
roots = ["ols.json"]
language-servers = ["ols"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "odin"
source = { git = "https://github.com/ap29600/tree-sitter-odin", rev = "b219207e49ffca2952529d33e94ed63b1b75c4f1" }

[[language]]
name = "scheme"
scope = "source.scheme"
injection-regex = "scheme"
file-types = ["ss", "scm", "kbd"]
shebangs = ["scheme", "guile", "chicken"]
comment-token = ";"
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "scheme"
source = { git = "https://github.com/6cdh/tree-sitter-scheme", rev = "af3af6c9356b936f8a515a1e449c32e804c2b1a8" }
