shell = "fish"
live_config_reload = true

[window]
padding = { x = 8, y = 8 }
opacity = 0.9
blur = true
startup_mode = "Maximized"

[scrolling]
history = 100_000

[font]
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular"} #Thin
bold = { family = "JetBrainsMono Nerd Font Propo", style = "Bold"}
italic = { family = "JetBrainsMono Nerd Font Propo", style = "Italic"}
bold_italic = { family = "JetBrainsMono Nerd Font Propo", style = "Bold Italic"}
size = 10


# Colors (Kanagawa Wave)
# Source https//github.com/rebelot/kanagawa.nvim

[colors.primary]
background = '#1f1f28'
foreground = '#dcd7ba'

[colors.normal]
black   = '#090618'
red     = '#c34043'
green   = '#76946a'
yellow  = '#c0a36e'
blue    = '#7e9cd8'
magenta = '#957fb8'
cyan    = '#6a9589'
white   = '#c8c093'

[colors.bright]
black   = '#727169'
red     = '#e82424'
green   = '#98bb6c'
yellow  = '#e6c384'
blue    = '#7fb4ca'
magenta = '#938aa9'
cyan    = '#7aa89f'
white   = '#dcd7ba'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'
